### PR TITLE
Disable cache in Ievkit::Job by default

### PR DESCRIPTION
**Pull request by csolem**
Disable cache by default to be able to use ievkit job without Redis.

### CODE REVIEW

**Comment by brunto** [comment]
IEV enable by default the cache, I think it's better to put this option in an environment variable.

**Comment by csolem** [comment]
Is it better to put this option in an environment variable in https://github.com/afimb/ievkit ?

**Comment by brunto** [comment]
Why not? If you want to test smtg you can quickly enable/disable the cache by setting the ENV.
BTW you're right we must add smtg to disable the cache in case you don't want to use redis.

**Comment by csolem** [comment]
I agree that it's better to read it as a env variable. But there are two repos here. So the question is if it's better to read this env variable in the repo _ievkit_ or the repo _ievkit_view_ ?

**Comment by brunto** [comment]
All the ENV variables must be set in IEVKIT. So I think we must put it in:
https://github.com/afimb/ievkit/blob/develop/config/application.example.yml
and
https://github.com/afimb/ievkit/blob/develop/lib/ievkit/client.rb#L28

**Pull request closed without merging**
